import type { Locale } from '$lib/stores/i18n.svelte';
import GOALPOSTS from '../../../pipeline/config/goalposts.json';

// Los rangos de goalpost citados en los textos de metodología se DERIVAN de la
// fuente canónica pipeline/config/goalposts.json. No hardcodear bounds acá: ante
// un re-baseline (bump vN) el texto se actualiza solo y nunca queda stale.
// (Antes el texto publicaba los goalposts v1.0 mientras el scoring usaba v1.1.)
const _GP = (GOALPOSTS as { indicators: Record<string, { lo: number; hi: number }> }).indicators;
function gpRange(key: string): string {
	const g = _GP[key];
	if (!g) throw new Error(`methodology: goalpost indicator desconocido "${key}"`);
	return `[${Math.round(g.lo)}, ${Math.round(g.hi)}]`.replace(/-/g, '−');
}

export interface LocalizedMethodologyContent {
	howToRead: Record<Locale, string>;
	implications: Record<Locale, string>;
	method: { es: string; en: string };
}

export const METHOD_COMPARABLE = {
	es: 'Normalización comparable: cada variable se normaliza con umbrales fijos (goalpost normalization, metodología UNDP-HDI) calculados sobre un universo pooled de referencia (NEA + región transfronteriza). Un valor de 0 representa el umbral mínimo y 100 el máximo, independientemente del territorio. Esto garantiza que un score de 60 tiene el mismo significado en cualquiera de los territorios comparables.\n\nTipos (clusters): las variables normalizadas se procesan con PCA para validar independencia (se descartan variables con |r| > 0.70). Luego k-means agrupa hexágonos con perfiles multivariados similares. Cada hexágono se asigna al tipo cuyo centroide es más cercano. La calidad se valida con coeficiente de silueta. Los tipos no son un ranking — son perfiles cualitativos distintos.',
	en: 'Comparable normalisation: each variable is normalised using fixed goalposts (goalpost normalisation, UNDP-HDI methodology) calculated over a pooled reference universe (NEA + trans-boundary region). A value of 0 represents the minimum threshold and 100 the maximum, regardless of territory. This ensures that a score of 60 carries the same meaning across any comparable territory.\n\nTypes (clusters): normalised variables are processed with PCA to validate independence (variables with |r| > 0.70 are discarded). K-means then groups hexagons with similar multivariate profiles. Each hexagon is assigned to the type whose centroid is nearest. Quality is validated using the silhouette coefficient. Types are not a ranking — they are qualitatively distinct profiles.',
};

export const METHOD_COMMON = {
	es: 'Valores por variable (0–100): cada variable se convierte a percentil dentro del territorio analizado. 50 = mediana del territorio, 100 = valor más alto del territorio.\n\nTipos (clusters): las variables estandarizadas se procesan con PCA para validar independencia (se descartan variables con |r| > 0.70). Luego k-means agrupa hexágonos con perfiles multivariados similares. Cada hexágono se asigna al tipo cuyo centroide es más cercano. La calidad se valida con coeficiente de silueta. Los tipos no son un ranking — son perfiles cualitativos distintos.',
	en: 'Values per variable (0–100): each variable is converted to a percentile within the analysed territory. 50 = territory median, 100 = highest value in the territory.\n\nTypes (clusters): standardised variables are processed with PCA to validate independence (variables with |r| > 0.70 are discarded). K-means then groups hexagons with similar multivariate profiles. Each hexagon is assigned to the type whose centroid is nearest. Quality is validated using the silhouette coefficient. Types are not a ranking — they are qualitatively distinct profiles.',
};

export const ANALYSIS_CONTENT: Record<string, LocalizedMethodologyContent> = {
	flood_risk: {
		howToRead: {
			es: 'El color responde a la pregunta de peligrosidad: presencia histórica de agua de cada hexágono (JRC Global Surface Water, Landsat 1984–2021). Azul = baja presencia (<5%); amarillo = presencia moderada (5–20%); rojo = alta presencia (>20%). Son porcentajes físicos, comparables entre territorios. La "extensión actual" es una segunda lectura distinta: una foto reciente de Sentinel-1 SAR cuya fecha figura en el recuadro de fuente. Seleccioná un departamento para ver el detalle por parcela.',
			en: 'Colour answers the hazard question: each hexagon\'s historical water presence (JRC Global Surface Water, Landsat 1984–2021). Blue = low presence (<5%); yellow = moderate (5–20%); red = high (>20%). These are physical percentages, comparable across territories. "Current extent" is a separate, second reading: a recent Sentinel-1 SAR snapshot whose date is shown in the source box. Select a department for parcel-level detail.',
			gn: "Sa'y ohechauka y rehegua historia hexágono ndive (JRC, Landsat 1984–2021). Hovy = michĩ (<5%); sa'yju = mbyte (5–20%); pytã = guasu (>20%). Eiporavo departamento ehecha hag̃ua mba'ekuaa.",
			pt: 'A cor responde à pergunta de perigosidade: presença histórica de água de cada hexágono (JRC Global Surface Water, Landsat 1984–2021). Azul = baixa presença (<5%); amarelo = moderada (5–20%); vermelho = alta (>20%). São percentagens físicas, comparáveis entre territórios. A "extensão atual" é uma segunda leitura distinta: uma imagem recente do Sentinel-1 SAR, cuja data consta no quadro de fonte. Selecione um departamento para ver os detalhes.',
		},
		implications: {
			es: 'Las zonas con alta presencia histórica de agua (>20%) enfrentan anegamientos recurrentes, afectando el valor inmobiliario, la habitabilidad y la infraestructura de servicios básicos (agua, cloacas). La recurrencia interanual distingue inundaciones estacionales predecibles de eventos extremos esporádicos. La extensión actual (Sentinel-1 SAR) agrega la lectura del presente: muestra qué superficie está cubierta por agua en la imagen más reciente, no solo el patrón de largo plazo.',
			en: 'Zones with high historical water presence (>20%) face recurrent flooding, affecting property values, habitability and basic service infrastructure (water, sanitation). Inter-annual recurrence distinguishes predictable seasonal floods from sporadic extreme events. Current extent (Sentinel-1 SAR) adds the present-day reading: it shows how much surface is water-covered in the latest image, not just the long-term pattern.',
			gn: "Yvate y rehegua historia ndive oĩva (>20%) pytu'u ikuai ko'ãva, imba'ete renda, óga oikohaguépe ha ykuaa joapy. Y oú jey jey ohechauka aramboty ymemoranduha mbarete.",
			pt: 'Zonas com alta presença histórica de água (>20%) enfrentam alagamentos recorrentes, afetando o valor imobiliário, a habitabilidade e a infraestrutura de serviços básicos (água, esgoto). A recorrência interanual distingue inundações sazonais previsíveis de eventos extremos esporádicos.',
		},
		method: {
			es: 'La capa combina dos fuentes que responden a dos preguntas distintas. (1) Peligrosidad histórica — JRC Global Surface Water v1.4 (Landsat, 1984–2021): presencia histórica = % del tiempo 1984–2021 con agua detectada; recurrencia interanual = % de años en que el agua reapareció; estacionalidad = meses promedio por año con agua en superficie. Para estimar riesgo, este registro largo es la herramienta correcta. (2) Estado actual — Sentinel-1 SAR (Copernicus): radar que atraviesa nubes y opera de noche, por eso es el sensor estándar para inundación activa (a diferencia del óptico, ciego bajo tormenta). Revisita ~6–12 días; extensión actual = % del hexágono cubierto por agua en la última imagen procesada, cuya fecha figura en el recuadro de fuente. Grilla H3 resolución 9. Sin normalización compuesta — valores directamente interpretables en sus unidades físicas.',
			en: 'The layer combines two sources answering two distinct questions. (1) Historical hazard — JRC Global Surface Water v1.4 (Landsat, 1984–2021): historical presence = % of time 1984–2021 with water detected; inter-annual recurrence = % of years water reappeared; seasonality = average months per year with surface water. For estimating risk, this long record is the right tool. (2) Current state — Sentinel-1 SAR (Copernicus): radar that penetrates clouds and works at night, which is why it is the standard sensor for active flooding (unlike optical, blind under storms). Revisit ~6–12 days; current extent = % of the hexagon covered by water in the latest processed image, whose date is shown in the source box. H3 resolution 9 grid. No composite normalisation — values directly interpretable in their physical units.',
		},
	},
	censo_temporal: {
		howToRead: {
			es: 'El color representa la densidad de población por hexágono. El selector temporal alterna entre el Censo 2022, el 2010 y el cambio (delta): en modo cambio, verde = la densidad creció, rojo = decreció. Cada hexágono mantiene su identidad en el tiempo (la grilla H3 es fija aunque los radios censales cambien de límites entre censos). Hacé click en un hexágono para ver la trayectoria completa de población y vivienda en los 4 censos (1991, 2001, 2010, 2022).',
			en: 'Colour represents population density per hexagon. The temporal selector switches between the 2022 Census, 2010, and the change (delta): in change mode, green = density grew, red = declined. Each hexagon keeps its identity over time (the H3 grid is fixed even though census-tract boundaries shift between censuses). Click a hexagon to see the full population and housing trajectory across the 4 censuses (1991, 2001, 2010, 2022).',
			gn: "Sa'y ohechauka tavaygua densidad hexágono-pe. Selector temporal omoambue 2022, 2010 ha moambue (delta): hovyũ = okakuaa, pytã = oguejy. Eikutu hexágono ehecha hag̃ua tavaygua ha óga rape 4 censo-pe (1991–2022).",
			pt: 'A cor representa a densidade populacional por hexágono. O seletor temporal alterna entre o Censo 2022, 2010 e a mudança (delta): no modo mudança, verde = a densidade cresceu, vermelho = caiu. Cada hexágono mantém sua identidade ao longo do tempo (a grade H3 é fixa, embora os setores censitários mudem de limites entre censos). Clique em um hexágono para ver a trajetória completa de população e moradia nos 4 censos (1991, 2001, 2010, 2022).',
		},
		implications: {
			es: 'La evolución de la densidad a 31 años revela patrones de urbanización, expansión periurbana y despoblamiento rural. El crecimiento concentrado señala presión sobre servicios (agua, cloacas, escuelas, transporte); la caída en núcleos densos puede indicar vaciamiento o suburbanización. Útil para planificar infraestructura y anticipar demanda futura.',
			en: 'The 31-year evolution of density reveals patterns of urbanisation, peri-urban expansion and rural depopulation. Concentrated growth signals pressure on services (water, sanitation, schools, transport); decline in dense cores can indicate hollowing-out or suburbanisation. Useful for infrastructure planning and anticipating future demand.',
			gn: "Densidad rape 31 ary ohechauka mba'éichapa okakuaa táva, oñembyaty peri-urbano ha okañy okaragua. Okakuaáva omoĩ presión servicios-re (y, mbo'ehao, jeguata).",
			pt: 'A evolução da densidade em 31 anos revela padrões de urbanização, expansão periurbana e despovoamento rural. O crescimento concentrado sinaliza pressão sobre serviços (água, esgoto, escolas, transporte); a queda em núcleos densos pode indicar esvaziamento ou suburbanização. Útil para planejar infraestrutura e antecipar demanda futura.',
		},
		method: {
			es: 'Totales de población y vivienda (recuento completo) de los 4 censos nacionales INDEC (1991, 2001, 2010, 2022). Cada año se reparte de forma areal a la grilla H3 resolución 9 sobre el universo poblado del territorio, con pesos renormalizados por radio de modo que la suma reconcilia exactamente con los totales provinciales publicados por INDEC. Se usa interpolación areal (no dasimétrica) en los 4 años por consistencia interna de la serie — los edificios actuales no pueden ponderar la población de 1991. La comparación temporal es válida porque la grilla H3 es la geografía invariante: el mismo hexágono físico se mide con los radios de cada censo. Cartografía de radios corregidos y estandarizados 1991–2022: Rodríguez & de Grande (CONICET). Solo provincias del NEA argentino (Misiones, Corrientes, Chaco, Formosa). Se reportan densidades comparables; los indicadores derivados (NBI, educación) no se comparan entre censos por cambios de definición de INDEC.',
			en: "Population and housing totals (full count) from the 4 INDEC national censuses (1991, 2001, 2010, 2022). Each year is areal-apportioned to the H3 resolution-9 grid over the territory's populated universe, with per-tract weights renormalised so the sum reconciles exactly to INDEC's published provincial totals. Areal (not dasymetric) interpolation is used for all 4 years for internal consistency of the series — present-day buildings cannot weight 1991 population. Temporal comparison is valid because the H3 grid is the invariant geography: the same physical hexagon is measured with each census's tracts. Corrected and standardised tract cartography 1991–2022: Rodríguez & de Grande (CONICET). Argentine NEA provinces only (Misiones, Corrientes, Chaco, Formosa). Comparable densities are reported; derived indicators (UBN, education) are not compared across censuses due to INDEC definitional changes.",
		},
	},
	agri_potential: {
		howToRead: {
			es: 'El color del mapa representa la cercanía al pH óptimo del suelo de cada hexágono, uno de los componentes físicos de la aptitud agrícola; la leyenda va de menor a mayor aptitud. Al hacer click se ve el perfil completo (calidad del suelo, régimen hídrico, acumulación térmica y topografía), el score compuesto y el tipo asignado por la clasificación multivariada (PCA + k-means). Comparable entre los territorios disponibles. Los valores /100 usan una escala fija regional — la misma en todos los territorios —, mientras que la flor del panel compara contra el promedio del territorio.',
			en: 'The map colour represents proximity to optimal soil pH for each hexagon, one of the physical components of agricultural suitability; the legend runs from lower to higher suitability. Clicking shows the full profile (soil quality, water regime, heat accumulation and topography), the composite score and the type assigned by the multivariate classification (PCA + k-means). Comparable across available territories. The /100 values use a fixed regional scale — the same across all territories —, while the panel\'s flower compares against the territory average.',
			gn: "Mapa sa'y ohechauka pH óptimo-pe mbojojáva (aptitud componente físico); leyenda oho michĩ guive tuicha aptitud peve. Eikutu ehecha hag̃ua perfil completo, score ha tipo (PCA + k-means). Ojoguáva tetã kuéra ojoguávape. Papapy /100 escala fija regional; yvoty ombojoja promedio local ndive.",
			pt: 'A cor do mapa representa a proximidade ao pH ótimo do solo de cada hexágono, um dos componentes físicos da aptidão agrícola; a legenda vai de menor a maior aptidão. Ao clicar, vê-se o perfil completo (qualidade do solo, regime hídrico, acumulação de calor e topografia), o score composto e o tipo atribuído pela classificação multivariada (PCA + k-means). Comparável entre os territórios disponíveis. Os valores /100 usam uma escala fixa regional — a mesma em todos os territórios —, enquanto a flor do painel compara contra a média do território.',
		},
		implications: {
			es: 'Los tipos reflejan configuraciones edafoclimáticas distintas: suelos ácidos con alta lluvia (aptitud para yerba mate), suelos neutros con calor acumulado (aptitud para tabaco/cítricos), y zonas con limitaciones múltiples.',
			en: 'Types reflect distinct edaphoclimatic configurations: acidic soils with high rainfall (suited for yerba mate), neutral soils with accumulated heat (suited for tobacco/citrus), and zones with multiple constraints.',
			gn: "Laja ohechauka yvy rehegua ambue ambue: yvai pH ka'aguyetépe (yerba mate), neutro GDD (tabaco/cítrico), ha yvy limitaciones hetáva.",
			pt: 'Os tipos refletem configurações edafoclimáticas distintas: solos ácidos com alta precipitação (aptidão para erva-mate), solos neutros com calor acumulado (aptidão para tabaco/cítricos) e zonas com limitações múltiplas.',
		},
		method: {
			es: `${METHOD_COMPARABLE.es} 5 variables con goalposts fijos: carbono orgánico del suelo ${gpRange('c_soc')} g/dm³, distancia a pH óptimo [0, 1.0], arcilla ${gpRange('c_clay')} g/kg, precipitación anual ${gpRange('c_precipitation')} mm/año, GDD base 10°C ${gpRange('c_gdd')} °C·día. Fuentes: SoilGrids v2 (ISRIC, 0–5cm), CHIRPS (precipitación), ERA5 (GDD), FABDEM (pendiente). Período: 2019–2024.`,
			en: `${METHOD_COMPARABLE.en} 5 variables with fixed goalposts: soil organic carbon ${gpRange('c_soc')} g/dm³, distance to optimal pH [0, 1.0], clay ${gpRange('c_clay')} g/kg, annual precipitation ${gpRange('c_precipitation')} mm/year, GDD base 10°C ${gpRange('c_gdd')} °C·day. Sources: SoilGrids v2 (ISRIC, 0–5cm), CHIRPS (precipitation), ERA5 (GDD), FABDEM (slope). Period: 2019–2024.`,
		},
	},
	forestry_aptitude: {
		howToRead: {
			es: "El color del mapa representa la precipitación anual (mm) de cada hexágono, uno de los principales drivers biofísicos de aptitud forestal; la leyenda va de menor a mayor precipitación. Al hacer click se ve el score de aptitud (0–100) estimado por un modelo de distribución de especie (SDM) entrenado sobre el Inventario Nacional de Plantaciones Forestales (DNDFI 2026) como presencia. El modelo distingue dos nichos: comercial (pino/eucalyptus) en Misiones y Corrientes, y especies nativas (Prosopis y otras) en Chaco y Formosa. Podés activar el overlay 'Plantaciones existentes' para ver la misma base que define el score. En Paraguay y Brasil el score es una extrapolación bioclimática, sin inventario local. Hexágonos sobre agua o urbano quedan sin pintar.",
			en: "The map colour represents annual precipitation (mm) of each hexagon, one of the main biophysical drivers of forestry suitability; the legend runs from lower to higher precipitation. Clicking shows the suitability score (0–100) estimated by a species distribution model (SDM) trained on the National Forestry Plantation Inventory (DNDFI 2026) as presence. The model distinguishes two niches: commercial (pine/eucalyptus) in Misiones and Corrientes, and native species (Prosopis and others) in Chaco and Formosa. Toggle the 'Existing plantations' overlay to see the same basis that defines the score. In Paraguay and Brazil the score is a bioclimatic extrapolation, with no local inventory. Hexagons over water or urban land are unpainted.",
			gn: "Mapa sa'y ohechauka ama ary pukukue (mm); leyenda oho michĩ guive tuicha ama peve. Eikutu ehecha hag̃ua score (0–100) SDM, oñembo'e Inventario Nacional de Plantaciones (DNDFI 2026) rehe. Mokõi nicho: comercial (Misiones, Corrientes) ha nativas (Chaco, Formosa). Paraguay ha Brasil-pe extrapolación bioclimática. Hexágono y-ári ha tëtã-pe ndaipytãi.",
			pt: "A cor do mapa representa a precipitação anual (mm) de cada hexágono, um dos principais drivers biofísicos de aptidão florestal; a legenda vai de menor a maior precipitação. Ao clicar, vê-se o score de aptidão (0–100) estimado por um modelo de distribuição de espécies (SDM) treinado sobre o Inventário Nacional de Plantações Florestais (DNDFI 2026) como presença. O modelo distingue dois nichos: comercial (pinho/eucalipto) em Misiones e Corrientes, e espécies nativas (Prosopis e outras) no Chaco e Formosa. Ative o overlay 'Plantações existentes' para ver a mesma base que define o score. No Paraguai e Brasil o score é uma extrapolação bioclimática, sem inventário local. Hexágonos sobre água ou área urbana ficam sem cor.",
		},
		implications: {
			es: "Score alto = condiciones análogas a zonas donde ya hay plantaciones (comerciales de pino/eucalyptus en Misiones y Corrientes; de especies nativas en Chaco y Formosa). En Paraguay y Brasil, interpretar como afinidad bioclimática transfronteriza, sin presencia local. Es una capa descriptiva, no prescriptiva: NO dice dónde se puede plantar legalmente (eso depende de normativa nacional, tenencia, comunidades), ni garantiza rendimiento comercial, ni reemplaza estudios de campo.",
			en: "High score = conditions analogous to zones where plantations already exist (commercial pine/eucalyptus in Misiones and Corrientes; native species in Chaco and Formosa). In Paraguay and Brazil, interpret as cross-border bioclimatic affinity, with no local presence. This is a descriptive layer, not a prescriptive one: it does NOT indicate where planting is legally permitted (that depends on national regulation, land tenure and communities), nor does it guarantee commercial yields, nor does it replace field surveys.",
			gn: "Yvate score = condiciones ojoguáva umi tenda ka'aguy oĩmava (comercial Misiones/Corrientes; nativas Chaco/Formosa). Paraguay ha Brasil-pe afinidad bioclimática. Capa descriptiva, ndaha'éi prescriptiva: ndohechái mávape oñemomba'éva ley rupive.",
			pt: 'Score alto = condições análogas às zonas onde já há plantações (comerciais de pinho/eucalipto em Misiones e Corrientes; de espécies nativas no Chaco e Formosa). No Paraguai e Brasil, interpretar como afinidade bioclimática transfronteiriça, sem presença local. É uma camada descritiva, não prescritiva: NÃO indica onde se pode plantar legalmente (isso depende de normativa nacional, posse de terra e comunidades), nem garante rendimento comercial, nem substitui estudos de campo.',
		},
		method: {
			es: `Random Forest (sklearn, 400 árboles, class_weight balanced) entrenado como SDM presencia-background. Presencia = Inventario Nacional de Plantaciones Forestales (DNDFI 2026, ~280.000 macizos) agregado a H3 con fracción plantada ≥ 0,10. Dos modelos por nicho ecológico, porque las plantaciones del NEA no son homogéneas: (1) comercial mesopotámico (Misiones + Corrientes, pino/eucalyptus, ~95.000 hexes de presencia), CV AUC = 0,90; (2) especies nativas del Parque Chaqueño (Chaco + Formosa, Prosopis y otras, ~1.420 hexes), CV AUC = 0,78. Background = muestra aleatoria (ratio 1:3). 23 covariables biofísicas a resolución H3: clima (ERA5 GDD, temperatura y radiación; CHIRPS precipitación y eventos extremos; TerraClimate déficit hídrico, VPD, humedad del suelo), suelo (SoilGrids arcilla/limo/arena/pH/SOC; HWSD drenaje, textura, profundidad radicular, AWC), terreno (SRTM pendiente, elevación, TWI, rugosidad), vegetación contextual (NDVI medio) y accesibilidad (tiempo a ciudad 50k). Validación: Group K-Fold espacial (5 folds, bloques H3 res 5); validación de presencia: las plantaciones reales puntúan muy por encima de la mediana territorial (Misiones 85 vs 60, Corrientes 78 vs 4, Chaco 76 vs 23, Formosa 78 vs 16). Score = probabilidad calibrada × 100. Paraguay y Brasil: extrapolación con el modelo comercial (sin inventario local). Tipos: k-means k=4 sobre covariables de hexágonos con score ≥ 40.`,
			en: `Random Forest (sklearn, 400 trees, class_weight balanced) trained as a presence-background SDM. Presence = National Forestry Plantation Inventory (DNDFI 2026, ~280,000 stands) aggregated to H3 with planted fraction ≥ 0.10. Two models, one per ecological niche, because NEA plantations are not homogeneous: (1) Mesopotamian commercial (Misiones + Corrientes, pine/eucalyptus, ~95,000 presence hexes), CV AUC = 0.90; (2) native species of the Chaco woodland (Chaco + Formosa, Prosopis and others, ~1,420 hexes), CV AUC = 0.78. Background = random sample (1:3 ratio). 23 biophysical covariates at H3 resolution: climate (ERA5 GDD, temperature and radiation; CHIRPS precipitation and extreme events; TerraClimate water deficit, VPD, soil moisture), soil (SoilGrids clay/silt/sand/pH/SOC; HWSD drainage, texture, root depth, AWC), terrain (SRTM slope, elevation, TWI, roughness), contextual vegetation (mean NDVI) and accessibility (travel time to 50k city). Validation: Spatial Group K-Fold (5 folds, H3 res-5 blocks); presence validation: real plantations score well above the territory median (Misiones 85 vs 60, Corrientes 78 vs 4, Chaco 76 vs 23, Formosa 78 vs 16). Score = calibrated probability × 100. Paraguay and Brazil: extrapolation with the commercial model (no local inventory). Types: k-means k=4 on covariates of hexagons with score ≥ 40.`,
		},
	},
	service_deprivation: {
		howToRead: {
			es: 'El color del mapa representa el nivel de NBI (Necesidades Básicas Insatisfechas) de cada hexágono, la variable principal de carencia; la leyenda va de baja a alta carencia. Al hacer click en un hexágono se ve su perfil completo (NBI, acceso a cloacas, calidad del piso, hacinamiento y acceso digital) y el tipo de carencia asignado por la clasificación multivariada (PCA + k-means). Solo se muestran hexágonos con edificaciones detectadas (crosswalk dasimétrico).',
			en: 'The map colour represents the UBN (Unsatisfied Basic Needs) level of each hexagon, the main deprivation variable; the legend runs from low to high deprivation. Clicking a hexagon shows its full profile (UBN, sanitation access, floor quality, overcrowding and digital access) and the deprivation type assigned by the multivariate classification (PCA + k-means). Only hexagons with detected buildings (dasymetric crosswalk) are shown.',
			gn: "Mapa sa'y ohechauka NBI cada hexágono-pe (carencia variable principal); leyenda oho michĩ guive tuicha peve. Eikutu hexágono-pe ehecha hag̃ua perfil completo (NBI, ykuaa, piso, ñembyaty, computadora) ha tipo (PCA + k-means). Opyta hexágono óga oĩhaguépe.",
			pt: 'A cor do mapa representa o nível de NBI (Necessidades Básicas Insatisfeitas) de cada hexágono, a variável principal de carência; a legenda vai de baixa a alta carência. Ao clicar num hexágono, vê-se o perfil completo (NBI, acesso a esgoto, qualidade do piso, superlotação e acesso digital) e o tipo de carência atribuído pela classificação multivariada (PCA + k-means). Apenas hexágonos com edificações detectadas (crosswalk dassimétrico) são exibidos.',
		},
		implications: {
			es: 'Los tipos separan carencia habitacional (piso inadecuado + hacinamiento), carencia de infraestructura (sin cloacas), y brecha digital (sin computadora). Cada configuración demanda intervenciones distintas: vivienda social, extensión de red cloacal, o programas de inclusión digital.',
			en: 'Types separate housing deprivation (inadequate floor + overcrowding), infrastructure deprivation (no sanitation), and digital divide (no computer). Each configuration calls for distinct interventions: social housing, sewerage extension, or digital inclusion programmes.',
			gn: "Laja oñemboikuaa carencia óga (piso vai + ñembyaty), ykuaa ỹre, ha computadora ỹre. Peteĩ-peteĩ configuración oguereko tembiapo ambue.",
			pt: 'Os tipos separam carência habitacional (piso inadequado + superlotação), carência de infraestrutura (sem esgoto) e exclusão digital (sem computador). Cada configuração demanda intervenções distintas: habitação social, extensão de rede de esgoto ou programas de inclusão digital.',
		},
		method: {
			es: `${METHOD_COMMON.es} 6 variables Censo Nacional 2022 (INDEC): NBI, sin cloacas (100 - pct_cloacas), piso inadecuado, hacinamiento, hacinamiento crítico, sin computadora (100 - pct_computadora). Crosswalk dasimétrico ponderado por edificios (2.8M footprints). KMO=0.73. (Normalización: percentil interno AR — consistente entre Corrientes, Chaco y Formosa. No comparable con PY ni BR.)`,
			en: `${METHOD_COMMON.en} 6 variables from the National Census 2022 (INDEC): UBN, no sewerage (100 − pct_sewerage), inadequate floor, overcrowding, critical overcrowding, no computer (100 − pct_computer). Dasymetric crosswalk weighted by buildings (2.8M footprints). KMO=0.73. (Normalisation: internal AR percentile — consistent across Corrientes, Chaco and Formosa. Not comparable with PY or BR.)`,
		},
	},
	health_access: {
		howToRead: {
			es: 'El color del mapa representa el tiempo de viaje al centro de salud más cercano de cada hexágono, la variable principal de acceso; la leyenda va de buen a mal acceso. Al hacer click se ve el perfil completo (tiempo a salud, cobertura sanitaria, vulnerabilidad social por NBI, presión demográfica de ancianos y menores, densidad poblacional) y el tipo de acceso asignado por la clasificación multivariada (PCA + k-means). Solo hexágonos con edificaciones.',
			en: 'The map colour represents the travel time to the nearest health facility for each hexagon, the main access variable; the legend runs from good to poor access. Clicking shows the full profile (time to health, health coverage, social vulnerability by UBN, demographic pressure from elderly and children, population density) and the access type assigned by the multivariate classification (PCA + k-means). Only hexagons with buildings.',
			gn: "Mapa sa'y ohechauka tape tesãi-rendápe (acceso variable principal); leyenda oho porã guive vai peve. Eikutu ehecha hag̃ua perfil completo (tape tesãi, joapy, NBI, ñembojekuaa, yvypóra) ha tipo (PCA + k-means). Hexágono óga oĩhaguépe.",
			pt: 'A cor do mapa representa o tempo de viagem ao centro de saúde mais próximo de cada hexágono, a variável principal de acesso; a legenda vai de bom a mau acesso. Ao clicar, vê-se o perfil completo (tempo à saúde, cobertura sanitária, vulnerabilidade social por NBI, pressão demográfica de idosos e crianças, densidade populacional) e o tipo de acesso atribuído pela classificação multivariada (PCA + k-means). Apenas hexágonos com edificações.',
		},
		implications: {
			es: 'Los tipos separan déficit por distancia (zonas rurales lejanas), déficit por saturación (zonas densas con alta proporción de población vulnerable), y déficit por cobertura (alto NBI con baja cobertura sanitaria). Cada configuración requiere respuestas distintas del sistema de salud.',
			en: 'Types separate distance-based deficit (remote rural zones), saturation-based deficit (dense zones with high vulnerable population shares), and coverage-based deficit (high UBN with low health coverage). Each configuration requires distinct responses from the health system.',
			gn: "Laja oñemboikuaa déficit tesãi: tape mombyry, yvypóra hetáva ha cobertura michĩva. Peteĩ-peteĩ configuración oguereko respuesta ambue.",
			pt: 'Os tipos separam déficit por distância (zonas rurais remotas), déficit por saturação (zonas densas com alta proporção de população vulnerável) e déficit por cobertura (alto NBI com baixa cobertura sanitária). Cada configuração requer respostas distintas do sistema de saúde.',
		},
		method: {
			es: `${METHOD_COMMON.es} 6 variables: tiempo motorizado a salud (Oxford MAP 2019), cobertura sanitaria, NBI, % adultos mayores, % menores 18, densidad poblacional (Censo 2022). Crosswalk dasimétrico. KMO=0.60. (Normalización: percentil interno AR — consistente entre Corrientes, Chaco y Formosa. No comparable con PY ni BR.)`,
			en: `${METHOD_COMMON.en} 6 variables: motorised travel time to health (Oxford MAP 2019), health coverage, UBN, % elderly, % under 18, population density (Census 2022). Dasymetric crosswalk. KMO=0.60. (Normalisation: internal AR percentile — consistent across Corrientes, Chaco and Formosa. Not comparable with PY or BR.)`,
		},
	},
	education_capital: {
		howToRead: {
			es: 'El color del mapa representa el porcentaje de población sin instrucción de cada hexágono, la variable principal; la leyenda va de alto a bajo capital educativo (más sin instrucción = menos capital). Al hacer click se ve el perfil completo (sin instrucción, secundario completo o más, educación superior, universitario) y el tipo asignado por la clasificación multivariada (PCA + k-means). Solo hexágonos con edificaciones.',
			en: 'The map colour represents the share of population with no formal education in each hexagon, the main variable; the legend runs from high to low educational capital (more no-schooling = less capital). Clicking shows the full profile (no schooling, secondary complete or above, higher education, university) and the type assigned by the multivariate classification (PCA + k-means). Only hexagons with buildings.',
			gn: "Mapa sa'y ohechauka mbo'e'ỹ porcentaje (variable principal); leyenda oho tuicha capital guive michĩ peve. Eikutu ehecha hag̃ua perfil completo (mbo'e'ỹ, secundario, terciario, universitario) ha tipo (PCA + k-means). Hexágono óga oĩhaguépe.",
			pt: 'A cor do mapa representa a percentagem de população sem instrução de cada hexágono, a variável principal; a legenda vai de alto a baixo capital educacional (mais sem instrução = menos capital). Ao clicar, vê-se o perfil completo (sem instrução, ensino médio completo ou mais, educação superior, universitário) e o tipo atribuído pela classificação multivariada (PCA + k-means). Apenas hexágonos com edificações.',
		},
		implications: {
			es: 'Los tipos distinguen zonas con alto capital humano (universidades cercanas, alta formación), zonas de educación media (secundario completo pero sin terciario), y zonas de bajo capital (alta proporción sin instrucción). El capital educativo es predictor de ingresos, salud y participación cívica.',
			en: 'Types distinguish zones with high human capital (nearby universities, high educational attainment), intermediate education zones (secondary complete but no tertiary), and low capital zones (high proportion with no formal education). Educational capital predicts income, health and civic participation.',
			gn: "Laja oñemboikuaa tëtã yvate capital educativo, mbyte ha michĩ. Mbo'e capital ohechauka ingreso, tesãi ha tetã-mba'e.",
			pt: 'Os tipos distinguem zonas com alto capital humano (universidades próximas, alta formação), zonas de educação média (ensino médio completo, sem terciário) e zonas de baixo capital (alta proporção sem instrução). O capital educacional prediz renda, saúde e participação cívica.',
		},
		method: {
			es: `${METHOD_COMMON.es} 4 variables Censo 2022: % sin instrucción, % secundario completo o más (umbral acumulativo), % educación superior (terciario + universitario), % universitario. Terciario y universitario son tracks paralelos en el sistema argentino. Crosswalk dasimétrico. KMO=0.71. (Normalización: percentil interno AR — consistente entre Corrientes, Chaco y Formosa. No comparable con PY ni BR.)`,
			en: `${METHOD_COMMON.en} 4 variables from Census 2022: % no formal education, % secondary complete or above (cumulative threshold), % higher education (tertiary + university), % university. Tertiary and university are parallel tracks in the Argentine system. Dasymetric crosswalk. KMO=0.71. (Normalisation: internal AR percentile — consistent across Corrientes, Chaco and Formosa. Not comparable with PY or BR.)`,
		},
	},
	education_flow: {
		howToRead: {
			es: 'El color del mapa representa la tasa de inasistencia escolar primaria (6–12 años) de cada hexágono, la variable principal; la leyenda va de buen a mal desempeño. Al hacer click se ve el perfil completo (inasistencia primaria, secundaria y maternidad adolescente) y el tipo asignado por la clasificación multivariada (PCA + k-means). Solo hexágonos con edificaciones.',
			en: 'The map colour represents the primary-school non-attendance rate (ages 6–12) of each hexagon, the main variable; the legend runs from good to poor performance. Clicking shows the full profile (primary and secondary non-attendance, adolescent motherhood) and the type assigned by the multivariate classification (PCA + k-means). Only hexagons with buildings.',
			gn: "Mapa sa'y ohechauka mbo'e oñeikéiha michĩ (6–12) (variable principal); leyenda oho porã guive vai peve. Eikutu ehecha hag̃ua perfil completo (oñeikéiva michĩ, yvate, sy adolescente) ha tipo (PCA + k-means). Hexágono óga oĩhaguépe.",
			pt: 'A cor do mapa representa a taxa de não frequência no ensino fundamental (6–12 anos) de cada hexágono, a variável principal; a legenda vai de bom a mau desempenho. Ao clicar, vê-se o perfil completo (não frequência fundamental e média, maternidade adolescente) e o tipo atribuído pela classificação multivariada (PCA + k-means). Apenas hexágonos com edificações.',
		},
		implications: {
			es: 'Los tipos separan deserción temprana (primaria), deserción tardía (secundaria) y embarazo adolescente como factor de exclusión educativa. La inasistencia primaria indica fallas básicas del sistema; la secundaria indica problemas de retención; la maternidad adolescente indica vulnerabilidad de género intersectada con pobreza.',
			en: "Types separate early drop-out (primary), late drop-out (secondary) and adolescent pregnancy as a factor of educational exclusion. Primary non-attendance signals basic system failures; secondary signals retention problems; adolescent motherhood signals gender vulnerability intersected with poverty.",
			gn: "Laja oñemboikuaa: mbo'e oñeikéiha (primaria), oñeikéiha (secundaria) ha sy adolescente. Primaria ohechauka falla básica; secundaria retención; maternidad adolescente vulnerabilidad.",
			pt: 'Os tipos separam evasão precoce (ensino fundamental), evasão tardia (ensino médio) e gravidez na adolescência como fator de exclusão educacional. A não frequência no fundamental indica falhas básicas do sistema; no médio, problemas de retenção; a maternidade adolescente, vulnerabilidade de gênero interseccionada com pobreza.',
		},
		method: {
			es: `${METHOD_COMMON.es} 3 variables Censo 2022: tasa de inasistencia 6-12 años, tasa de inasistencia 13-18 años, tasa de maternidad adolescente. Variables directas (mayor = peor flujo). Crosswalk dasimétrico. KMO=0.61. (Normalización: percentil interno AR — consistente entre Corrientes, Chaco y Formosa. No comparable con PY ni BR.)`,
			en: `${METHOD_COMMON.en} 3 variables from Census 2022: non-attendance rate 6–12 years, non-attendance rate 13–18 years, adolescent motherhood rate. Direct variables (higher = worse performance). Dasymetric crosswalk. KMO=0.61. (Normalisation: internal AR percentile — consistent across Corrientes, Chaco and Formosa. Not comparable with PY or BR.)`,
		},
	},
	land_use: {
		howToRead: {
			es: 'El mapa muestra la composición de cobertura del suelo de cada hexágono. El color representa la fracción arbórea; la leyenda va de poca a alta cobertura arbórea. El panel de detalle muestra las 9 clases de Dynamic World: árboles, cultivos, pasturas, arbustos, construido, agua, vegetación inundada, suelo desnudo y nieve/hielo. Las fracciones son probabilidades medias por hexágono y suman ≈ 1.',
			en: 'The map shows the land-cover composition of each hexagon. Colour encodes the tree fraction; the legend runs from low to high tree cover. The detail panel shows the 9 Dynamic World classes: trees, crops, grass, shrub, built, water, flooded vegetation, bare soil and snow/ice. Fractions are mean per-hexagon probabilities and sum to ≈ 1.',
			gn: "Mapa ohechauka hexágono kuéra cobertura: sa'y ohechauka ka'aguy fracción. Panel ohechauka 9 clase Dynamic World: yvyra, temity, pasto, ka'avo, táva, y, ñana y, yvy ha roy.",
			pt: 'O mapa mostra a composição da cobertura do solo de cada hexágono. A cor codifica a fração arbórea (mais verde = mais árvores). O painel mostra as 9 classes do Dynamic World: árvores, cultivos, pastagem, arbustos, construído, água, vegetação inundada, solo exposto e neve/gelo. As frações são probabilidades médias por hexágono e somam ≈ 1.',
		},
		implications: {
			es: 'La fracción arbórea separa selva/bosque (alto verde) de frentes agrícolas, pasturas y áreas urbanas (bajo verde). Al ser un producto global homogéneo, Dynamic World permite comparar la cobertura directamente entre Misiones, Itapúa, el Chaco y el sur de Brasil, sin los sesgos de clasificaciones nacionales distintas (MapBiomas AR ≠ PY ≠ BR). El detalle de las 9 clases ayuda a distinguir, p. ej., cultivo anual de pastura, o construido de suelo desnudo.',
			en: "Tree fraction separates forest (high green) from agricultural frontiers, pasture and urban areas (low green). As a homogeneous global product, Dynamic World allows cover to be compared directly across Misiones, Itapúa, the Chaco and southern Brazil, without the biases of differing national classifications (MapBiomas AR ≠ PY ≠ BR). The 9-class breakdown helps separate, e.g., annual crops from pasture, or built-up from bare soil.",
			gn: "Ka'aguy fracción ombojoavy selva (hovyũ guasu) ha temity/táva (hovyũ michĩ). Dynamic World ha'e producto global → ojoguáva opa tetãre, MapBiomas mba'e'ỹre.",
			pt: 'A fração arbórea separa floresta (verde alto) de fronteiras agrícolas, pastagem e áreas urbanas (verde baixo). Sendo um produto global homogêneo, o Dynamic World permite comparar a cobertura diretamente entre Misiones, Itapúa, o Chaco e o sul do Brasil, sem os vieses de classificações nacionais distintas (MapBiomas AR ≠ PY ≠ BR).',
		},
		method: {
			es: 'Fuente: Dynamic World V1 (Google / World Resources Institute), clasificación de cobertura del suelo a 10 m derivada de Sentinel-2 mediante deep learning (near-real-time). Cada hexágono H3 res-9 recibe la fracción media [0–1] de las 9 clases: agua, árboles, pasturas, vegetación inundada, cultivos, arbustos, construido, suelo desnudo y nieve/hielo. El color del mapa usa la fracción arbórea (frac_trees). Producto global con método idéntico en Argentina, Paraguay y Brasil → directamente comparable entre territorios, sin las discontinuidades de las colecciones nacionales de MapBiomas.',
			en: 'Source: Dynamic World V1 (Google / World Resources Institute), 10 m land-cover classification derived from Sentinel-2 via deep learning (near-real-time). Each H3 res-9 hexagon receives the mean fraction [0–1] of the 9 classes: water, trees, grass, flooded vegetation, crops, shrub, built, bare soil and snow/ice. Map colour uses the tree fraction (frac_trees). A global product with an identical method across Argentina, Paraguay and Brazil → directly comparable across territories, without the discontinuities of national MapBiomas collections.',
		},
	},
	sociodemographic: {
		howToRead: {
			es: 'El color del mapa representa el porcentaje de hogares con NBI de cada hexágono, la variable principal; la leyenda va de bajo a alto NBI. Al hacer click se ve el perfil completo (densidad poblacional, NBI, hacinamiento, tenencia de vivienda, tamaño del hogar y acceso digital) y el tipo sociodemográfico asignado por la clasificación multivariada (PCA + k-means).',
			en: 'The map colour represents the share of households with UBN in each hexagon, the main variable; the legend runs from low to high UBN. Clicking shows the full profile (population density, UBN, overcrowding, housing tenure, household size and digital access) and the sociodemographic type assigned by the multivariate classification (PCA + k-means).',
			gn: "Mapa sa'y ohechauka NBI porcentaje (variable principal); leyenda oho michĩ guive tuicha peve. Eikutu ehecha hag̃ua perfil completo (densidad, NBI, ñembyaty, óga tenencia, óga tuichakue, computadora) ha tipo (PCA + k-means).",
			pt: 'A cor do mapa representa a percentagem de domicílios com NBI de cada hexágono, a variável principal; a legenda vai de baixo a alto NBI. Ao clicar, vê-se o perfil completo (densidade populacional, NBI, superlotação, posse da habitação, tamanho do domicílio e acesso digital) e o tipo sociodemográfico atribuído pela classificação multivariada (PCA + k-means).',
		},
		implications: {
			es: 'Los tipos distinguen zonas urbanas densas con bajo NBI, periferias con hacinamiento y pobreza, y zonas rurales dispersas con alta propiedad pero baja conectividad. Esta clasificación multivariada evita reducir la complejidad social a un solo indicador.',
			en: 'Types distinguish dense urban zones with low UBN, peripheries with overcrowding and poverty, and sparse rural zones with high home ownership but low connectivity. This multivariate classification avoids reducing social complexity to a single indicator.',
			gn: "Laja oñemboikuaa tëtã denso NBI michĩháva, periferia ñembyaty ha NBI yvateháva, ha yvy rembe'ý propietarióva. Ojeporavo variables hetaháicha.",
			pt: 'Os tipos distinguem zonas urbanas densas com baixo NBI, periferias com superlotação e pobreza e zonas rurais dispersas com alta propriedade mas baixa conectividade. Esta classificação multivariada evita reduzir a complexidade social a um único indicador.',
		},
		method: {
			es: `${METHOD_COMMON.es} 6 variables del Censo Nacional 2022 (INDEC): densidad hab/km², % NBI, % hacinamiento, % propietarios, tamaño medio hogar, % computadora. Variables a nivel radio censal, agregadas a H3 vía crosswalk ponderado por área.`,
			en: `${METHOD_COMMON.en} 6 variables from the National Census 2022 (INDEC): population density (hab/km²), % UBN, % overcrowding, % home ownership, mean household size, % computer ownership. Variables at census tract level, aggregated to H3 via area-weighted crosswalk.`,
		},
	},
	economic_activity: {
		howToRead: {
			es: 'El color del mapa representa la radiancia nocturna (luces VIIRS) de cada hexágono, la variable principal y proxy de actividad económica; la leyenda va de poca a alta actividad nocturna. Al hacer click se ve el perfil completo (empleo, actividad económica, formación universitaria, luces nocturnas y densidad edilicia) y el tipo asignado por la clasificación multivariada (PCA + k-means).',
			en: 'The map colour represents night-time radiance (VIIRS lights) of each hexagon, the main variable and a proxy for economic activity; the legend runs from low to high night-time activity. Clicking shows the full profile (employment, economic activity, university education, night lights and building density) and the type assigned by the multivariate classification (PCA + k-means).',
			gn: "Mapa sa'y ohechauka radiancia pyhare (VIIRS) (variable principal, tembiapo proxy); leyenda oho michĩ guive tuicha peve. Eikutu ehecha hag̃ua perfil completo (empleo, actividad, universitario, luces, densidad óga) ha tipo (PCA + k-means).",
			pt: 'A cor do mapa representa a radiância noturna (luzes VIIRS) de cada hexágono, a variável principal e proxy de atividade econômica; a legenda vai de pouca a alta atividade noturna. Ao clicar, vê-se o perfil completo (emprego, atividade econômica, formação universitária, luzes noturnas e densidade edilícia) e o tipo atribuído pela classificação multivariada (PCA + k-means).',
		},
		implications: {
			es: 'Los tipos separan centros económicos consolidados (alto empleo + universitarios + luces), periferias activas con posible informalidad (alta actividad, bajo empleo formal), y zonas rurales de baja actividad económica. La radiancia nocturna (VIIRS) es un proxy robusto de actividad que complementa los datos censales.',
			en: 'Types separate consolidated economic centres (high employment + university graduates + night lights), active peripheries with possible informality (high activity, low formal employment), and rural zones with low economic activity. Night-time radiance (VIIRS) is a robust proxy for activity that complements census data.',
			gn: "Laja oñemboikuaa centro económico, periferia activa informalidad ndive, ha yvy michĩ actividad. VIIRS oñepyrũ proxy robusta mba'e tembiapo-pe.",
			pt: 'Os tipos separam centros econômicos consolidados (alto emprego + universitários + luzes), periferias ativas com possível informalidade (alta atividade, baixo emprego formal) e zonas rurais de baixa atividade econômica. A radiância noturna (VIIRS) é um proxy robusto de atividade que complementa os dados censitários.',
		},
		method: {
			es: `${METHOD_COMMON.es} 5 variables: tasa de empleo y actividad (Censo 2022 INDEC, 14+ años), % universitarios (Censo 2022), radiancia nocturna VIIRS 500m (media anual 2025, valor crudo en nW/cm²/sr), densidad edilicia Global Building Atlas 2025 (edificios/km² por hexágono, valor crudo). Variables censales agregadas a H3 vía crosswalk; VIIRS y densidad medidas directamente a nivel hexágono en las cuatro provincias del NEA.`,
			en: `${METHOD_COMMON.en} 5 variables: employment rate and activity rate (Census 2022 INDEC, 14+ years), % university graduates (Census 2022), VIIRS 500m night-time radiance (2025 annual mean, raw nW/cm²/sr), building density Global Building Atlas 2025 (buildings/km² per hexagon, raw value). Census variables aggregated to H3 via crosswalk; VIIRS and density measured directly at hexagon level across the four NEA provinces.`,
		},
	},
	eudr: {
		howToRead: {
			es: 'El mapa colorea el riesgo de deforestación post-2020 por hexágono (~5 km², H3 res-7). Color cálido (rojo) = mayor pérdida forestal o fuego después del corte EUDR (31/12/2020). Hacé clic en una unidad (departamento, distrito o municipio) para ver el desglose plantación vs bosque nativo de su pérdida — distingue la cosecha de una forestación (conforme) de la deforestación de bosque nativo. Cobertura: NEA argentino (Misiones, Corrientes, Chaco y Formosa) + Paraguay + sur de Brasil. Para análisis a nivel parcela (res-9 ~0,1 km², subiendo polígono o coordenadas) está la herramienta dedicada en /eudr/check.',
			en: 'The map colours post-2020 deforestation risk per hexagon (~5 km², H3 res-7). Warm colour (red) = greater forest loss or fire after the EUDR cut-off (31/12/2020). Click a unit (department, district or municipality) to see the plantation-vs-native-forest breakdown of its loss — distinguishing a plantation harvest (compliant) from native-forest deforestation. Coverage: NE Argentina (Misiones, Corrientes, Chaco and Formosa) + Paraguay + southern Brazil. For parcel-level analysis (res-9 ~0.1 km², by uploading a polygon or coordinates) use the dedicated tool at /eudr/check.',
			gn: "Mapa ohechauka riesgo deforestación post-2020 hexágono ndive (~5 km², H3 res-7). Color pyta = yvate pérdida forestal o tata post EUDR corte (31/12/2020). Eikutu peteĩ unidad-re (departamento, distrito) rehechápe plantación vs ka'aguy nativo desglose. Cobertura: Argentina norte (NEA + NOA) + Paraguay + Brasil sur. Parcela-pe (res-9) eipuru /eudr/check.",
			pt: 'O mapa colore o risco de desmatamento pós-2020 por hexágono (~5 km², H3 res-7). Cor quente (vermelho) = maior perda florestal ou fogo após o corte EUDR (31/12/2020). Clique numa unidade (departamento, distrito ou município) para ver a divisão plantação vs floresta nativa da sua perda — distinguindo a colheita de uma plantação (conforme) do desmatamento de floresta nativa. Cobertura: norte argentino (NEA + NOA, 10 províncias) + Paraguai + sul do Brasil. Para análise por parcela (res-9 ~0,1 km², enviando polígono ou coordenadas) use a ferramenta dedicada em /eudr/check.',
		},
		implications: {
			es: 'Hexágonos con deforestación de bosque nativo post-2020 representan riesgo de no-conformidad bajo la Regulación (UE) 2023/1115. La distinción plantación / bosque nativo (baseline MapBiomas 2020) atenúa un falso positivo clave para el sector forestal: la pérdida sobre una plantación que ya existía en 2020 es compatible con un ciclo de cosecha (no con deforestación de bosque nativo), mientras que una zona que era nativa en 2020 y hoy figura como plantación es una posible conversión a verificar. Estas son señales indicativas, no veredictos de cumplimiento: la pérdida Hansen puede deberse a cosecha, fuego, manejo o conversión, y su clasificación de causa requiere verificación. Exportaciones de commodities EUDR (soja, carne, madera) de zonas con pérdida sobre bosque nativo ameritan due diligence reforzado. Análisis orientativo (informe técnico de soporte) — la verificación formal requiere geometría parcelaria oficial, trazabilidad documental y due diligence profesional independiente.',
			en: 'Hexagons with post-2020 native-forest deforestation represent non-compliance risk under Regulation (EU) 2023/1115. The plantation / native-forest distinction (MapBiomas 2020 baseline) tempers a key false positive for the forestry sector: loss over a plantation that already existed in 2020 is consistent with a harvest cycle (not native-forest deforestation), whereas an area that was native in 2020 and is plantation today is a possible conversion to verify. These are indicative signals, not compliance verdicts: Hansen loss may stem from harvest, fire, management or conversion, and determining its cause requires verification. EUDR commodity exports (soy, beef, timber) from zones with loss over native forest warrant enhanced due diligence. Indicative analysis (technical support report) — formal verification requires official parcel geometry, documentary traceability and independent professional due diligence.',
			gn: "Hexágono ka'aguy nativo deforestación post-2020 ndive = riesgo Regulación UE 2023/1115. Distinción plantación / ka'aguy nativo (baseline 2020) ojokupyty falso positivo forestal-pe: cosecha plantación oĩmava'ekue 2020-pe ndaha'éi deforestación (conforme); conversión nativo→plantación post-2020 ndaha'éi conforme. Commodity EUDR (soja, mburu, yvyra) deforestación nativa-gui oguereko due diligence reforzado. Análisis orientativo — verificación formal ikatu geometría parcelaria oficial rehegua.",
			pt: 'Hexágonos com desmatamento de floresta nativa pós-2020 representam risco de não conformidade sob o Regulamento (UE) 2023/1115. A distinção plantação / floresta nativa (baseline MapBiomas 2020) evita um falso positivo chave para o setor florestal: colher uma plantação que já existia em 2020 NÃO é desmatamento (é conforme), enquanto uma conversão de nativo para plantação após 2020 É não conforme. Exportações de commodities EUDR (soja, carne, madeira) de zonas com desmatamento nativo requerem due diligence reforçado. Análise indicativa (relatório técnico de apoio) — a verificação formal requer geometria parcelária oficial, rastreabilidade documental e due diligence profissional independente.',
		},
		method: {
			es: `Score compuesto 0-100: 70% pérdida forestal post-2020 (Hansen GFC v1.13, Landsat, remuestreado a 100 m) + 20% área quemada post-2020 (MODIS MCD64A1, 500m) + 10% pérdida de cobertura previa. Cutoff EUDR: 31/12/2020. Resolución: el visor del mapa principal agrega a H3 res-7 (~5 km²) por rendimiento; la herramienta /eudr/check opera a res-9 (~0,1 km²). El dato satelital subyacente es de 100 m, que es el piso de precisión efectivo. Cobertura: 4 provincias del NEA argentino (Misiones, Corrientes, Chaco, Formosa) + todo Paraguay (17 departamentos) + 3 estados del sur de Brasil (Paraná, Santa Catarina, Rio Grande do Sul). Distinción plantación / bosque nativo: cada hexágono se cruza con MapBiomas Argentina Colección 1 (clase 9 = silvicultura) en DOS fechas — el corte EUDR 2020 y el estado actual. El baseline 2020 permite leer la pérdida según la cobertura previa al corte: pérdida sobre una zona que ya era plantación en 2020 es compatible con un ciclo de cosecha (no con deforestación de nativo); la vegetación nativa se separa además en bosque (formación forestal, MapBiomas clase 3) y monte/sabana nativa (formación sabánica, clases 4+6) — distinción relevante porque Chaco y Corrientes son mayormente monte/sabana, no selva cerrada, y "bosque" no debe sobre-vendarse ahí; y una zona que era bosque en 2020 y hoy figura como plantación es una posible conversión a verificar. Son señales indicativas, no veredictos de cumplimiento. La distinción cubre las 4 provincias del NEA argentino (Misiones, Corrientes, Chaco, Formosa); Paraguay y Brasil quedan "sin dato de plantación" (MapBiomas allí no tiene clase de silvicultura usable).`,
			en: `Composite score 0–100: 70% post-2020 forest loss (Hansen GFC v1.13, Landsat, resampled to 100 m) + 20% post-2020 burned area (MODIS MCD64A1, 500m) + 10% prior cover loss. EUDR cut-off: 31/12/2020. Resolution: the main-map viewer aggregates to H3 res-7 (~5 km²) for performance; the /eudr/check tool operates at res-9 (~0.1 km²). The underlying satellite data is 100 m, which is the effective precision floor. Coverage: 4 provinces of NE Argentina (Misiones, Corrientes, Chaco, Formosa) + all of Paraguay (17 departments) + 3 southern Brazilian states (Paraná, Santa Catarina, Rio Grande do Sul). Plantation / native-forest distinction: each hexagon is cross-referenced with MapBiomas Argentina Collection 1 (class 9 = forestry plantation) at TWO dates — the 2020 EUDR cut-off and the current state. The 2020 baseline lets the loss be read by the pre-cutoff cover: loss over an area that was already plantation in 2020 is consistent with a harvest cycle (not native-forest deforestation); native vegetation is further split into forest (forest formation, MapBiomas class 3) and native savanna/woodland (savanna formation, classes 4+6) — a relevant distinction because Chaco and Corrientes are mostly savanna/woodland rather than closed forest, so "forest" should not be overstated there; and an area that was forest in 2020 and is plantation today is a possible conversion to verify. These are indicative signals, not compliance verdicts. The distinction covers the 4 provinces of NE Argentina (Misiones, Corrientes, Chaco, Formosa); Paraguay and Brazil are flagged "no plantation data" (MapBiomas there has no usable forestry-plantation class).`,
		},
	},
	accessibility: {
		howToRead: {
			es: 'El color del mapa representa el tiempo de viaje motorizado a la capital departamental de cada hexágono (en minutos), la variable principal de conectividad; la leyenda va de cerca a lejos del capital. Al hacer click se ve el perfil completo (tiempo a capital, a la ciudad ≥50k, distancia a hospital, escuela secundaria y ruta principal) y el tipo asignado por la clasificación multivariada (PCA + k-means). Comparable entre los territorios disponibles: mismas fuentes y metodología.',
			en: 'The map colour represents motorised travel time to the departmental capital for each hexagon (in minutes), the main connectivity variable; the legend runs from near to far from the capital. Clicking shows the full profile (time to capital, to the nearest city ≥50k, distance to hospital, secondary school and primary road) and the type assigned by the multivariate classification (PCA + k-means). Comparable across available territories: same sources and methodology.',
			gn: "Mapa sa'y ohechauka tape capital departamental-pe (minuto-pe), conectividad variable principal; leyenda oho aguĩ guive mombyry peve. Eikutu ehecha hag̃ua perfil completo (tape capital, tëtã ≥50k, hospital, mbo'ehóga, ruta) ha tipo (PCA + k-means). Ojoguáva tetã kuéra ojoguávape.",
			pt: 'A cor do mapa representa o tempo de viagem motorizada à capital departamental de cada hexágono (em minutos), a variável principal de conectividade; a legenda vai de perto a longe da capital. Ao clicar, vê-se o perfil completo (tempo à capital, à cidade ≥50k, distância a hospital, escola secundária e via principal) e o tipo atribuído pela classificação multivariada (PCA + k-means). Comparável entre os territórios disponíveis: mesmas fontes e metodologia.',
		},
		implications: {
			es: 'Los tipos distinguen conectividad plena (cercanía a servicios y rutas), accesibilidad parcial (cerca de ruta pero lejos de servicios especializados), y aislamiento funcional (lejos de todo). La comparación entre territorios revela diferencias estructurales en conectividad según topografía y densidad vial.',
			en: 'Types distinguish full connectivity (proximity to services and roads), partial accessibility (near a road but distant from specialised services), and functional isolation (far from everything). Cross-territory comparison reveals structural differences in connectivity according to topography and road density.',
			gn: "Laja oñemboikuaa jeike opyta, jeike ayvúva ha jy mombyry. Oñembojoaju territorios ohechauka ambue ambue connectividad.",
			pt: 'Os tipos distinguem conectividade plena (proximidade a serviços e vias), acessibilidade parcial (próximo a uma via, mas distante de serviços especializados) e isolamento funcional (longe de tudo). A comparação entre territórios revela diferenças estruturais em conectividade conforme a topografia e a densidade viária.',
		},
		method: {
			es: `${METHOD_COMPARABLE.es} 5 variables con goalposts fijos: tiempo a capital ${gpRange('c_travel_capital')} min, tiempo a ciudad ≥50k ${gpRange('c_travel_cabecera')} min, distancia a hospital ${gpRange('c_dist_hospital')} km, distancia a escuela ${gpRange('c_dist_school')} km, distancia a ruta principal ${gpRange('c_dist_road')} km. El "tiempo a capital" se mide a la capital departamental de cada territorio, calculado como ruta de mínimo costo sobre la superficie de fricción Oxford MAP 2019. Fuentes: Oxford MAP friction_surface_2019 + accessibility_to_cities_2015 + OpenStreetMap (hospitales, escuelas, rutas).`,
			en: `${METHOD_COMPARABLE.en} 5 variables with fixed goalposts: time to department capital ${gpRange('c_travel_capital')} min, time to city ≥50k ${gpRange('c_travel_cabecera')} min, distance to hospital ${gpRange('c_dist_hospital')} km, distance to school ${gpRange('c_dist_school')} km, distance to primary road ${gpRange('c_dist_road')} km. "Time to capital" is measured to each territory's departmental capital, computed as a least-cost path over the Oxford MAP 2019 friction surface. Sources: Oxford MAP friction_surface_2019 + accessibility_to_cities_2015 + OpenStreetMap (hospitals, schools, roads).`,
		},
	},
	carbon_stock: {
		howToRead: {
			es: 'El mapa muestra el stock de carbono total por hexágono (biomasa aérea + subterránea + carbono del suelo) y el balance anual de emisiones/remociones. Colores más intensos indican mayor stock. Los valores se muestran en unidades físicas (tC/ha, MgCO2/ha). Comparable entre los territorios disponibles.',
			en: 'The map shows the total carbon stock per hexagon (above-ground + below-ground biomass + soil carbon) and the annual emissions/removals balance. More intense colours indicate higher stock. Values are shown in physical units (tC/ha, MgCO₂/ha). Comparable across available territories.',
			gn: "Mapa ohechauka carbono stock hexágono-pe (biomasa + suelo) ha balance emisiones/remociones. Pytã mombyry = yvate stock. Ojoguáva tetã kuéra ojoguávape.",
			pt: 'O mapa mostra o estoque total de carbono por hexágono (biomassa aérea + subterrânea + carbono do solo) e o balanço anual de emissões/remoções. Cores mais intensas indicam maior estoque. Os valores são exibidos em unidades físicas (tC/ha, MgCO₂/ha). Comparável entre os territórios disponíveis.',
		},
		implications: {
			es: 'Las zonas de alto stock con balance neto negativo (sumidero) son candidatas para créditos de carbono por conservación. Las zonas de alto stock con balance positivo (emisor) son prioridad para intervención REDD+. Las zonas de bajo stock con alta productividad (NPP) tienen potencial de restauración y secuestro futuro. *Valor teórico del carbono: estimación de referencia calculada como stock total x 3.67 (conversión C a CO2) x USD 10/tCO2e (mediana del mercado voluntario 2024, Ecosystem Marketplace 2024). No representa un precio de venta ni el valor realizable de un predio. La monetización efectiva requiere un proyecto certificado (VCS, Gold Standard) con línea base, adicionalidad demostrada y costos de transacción que reducen significativamente el valor neto.',
			en: 'High-stock zones with a net negative balance (carbon sink) are candidates for conservation carbon credits. High-stock zones with a positive balance (carbon source) are a priority for REDD+ intervention. Low-stock zones with high productivity (NPP) have restoration potential and future sequestration capacity. *Theoretical carbon value: reference estimate calculated as total stock × 3.67 (C to CO₂ conversion) × USD 10/tCO₂e (voluntary market median 2024, Ecosystem Marketplace 2024). This does not represent a sale price or the realisable value of any property. Effective monetisation requires a certified project (VCS, Gold Standard) with a documented baseline, demonstrated additionality and transaction costs that significantly reduce net value.',
			gn: "Yvate stock, balance negativo (sumidero) = candidato crédito carbono. Yvate stock, balance positivo (emisor) = prioridad REDD+. Michĩ stock, yvate NPP = potencial restauración. *Valor carbono: stock × 3.67 × USD 10/tCO2e (mediana mercado voluntario 2024). Ndahéi precio venta.",
			pt: 'Zonas de alto estoque com balanço líquido negativo (sumidouro) são candidatas a créditos de carbono por conservação. Zonas de alto estoque com balanço positivo (fonte) são prioridade para intervenção REDD+. Zonas de baixo estoque com alta produtividade (NPP) têm potencial de restauração e sequestro futuro. *Valor teórico do carbono: estimativa de referência calculada como estoque total × 3,67 (conversão C para CO₂) × USD 10/tCO₂e (mediana do mercado voluntário 2024, Ecosystem Marketplace 2024). Não representa um preço de venda nem o valor realizável de um imóvel. A monetização efetiva requer um projeto certificado (VCS, Gold Standard) com linha de base, adicionalidade demonstrada e custos de transação que reduzem significativamente o valor líquido.',
		},
		method: {
			es: `${METHOD_COMPARABLE.es} Score compuesto: media geométrica de biomasa aérea ${gpRange('c_agb_cci')} Mg/ha, carbono total ${gpRange('c_total_carbon')} tC/ha, carbono orgánico del suelo ${gpRange('c_soc')} g/dm³ y flujo neto ${gpRange('c_net_flux')} MgCO2/ha. Biomasa aérea: ESA CCI Biomass v6 (100m, Santoro et al. 2024) + GEDI L4B lidar (1km, validación). Biomasa subterránea: Cairns et al. (1997): BGB = 0.489 × AGB^0.89. SOC: SoilGrids v2 (ISRIC, 0–30cm). Flujo de carbono: Harris et al. (2021) / Global Forest Watch (emisiones + remociones + balance neto, 30m, 2001–2024). Productividad: MODIS MOD17A3HGF NPP (500m, 2019–2024). Total carbon = AGB × 0.47 + BGB × 0.47 + SOC. Precio de referencia: Ecosystem Marketplace (2024).`,
			en: `${METHOD_COMPARABLE.en} Composite score: geometric mean of above-ground biomass ${gpRange('c_agb_cci')} Mg/ha, total carbon ${gpRange('c_total_carbon')} tC/ha, soil organic carbon ${gpRange('c_soc')} g/dm³ and net flux ${gpRange('c_net_flux')} MgCO₂/ha. Above-ground biomass: ESA CCI Biomass v6 (100m, Santoro et al. 2024) + GEDI L4B lidar (1km, validation). Below-ground biomass: Cairns et al. (1997): BGB = 0.489 × AGB^0.89. SOC: SoilGrids v2 (ISRIC, 0–30cm). Carbon flux: Harris et al. (2021) / Global Forest Watch (emissions + removals + net balance, 30m, 2001–2024). Productivity: MODIS MOD17A3HGF NPP (500m, 2019–2024). Total carbon = AGB × 0.47 + BGB × 0.47 + SOC. Reference price: Ecosystem Marketplace (2024).`,
		},
	},
	pm25_drivers: {
		howToRead: {
			es: 'El mapa muestra la calidad del aire en cada hexágono, medida como concentración media de PM2.5 (partículas finas < 2.5 µm) y descompuesta en cuatro drivers: fuego regional, clima, terreno y vegetación. Valor alto (colores cálidos/rojos) = mayor concentración de PM2.5 (peor calidad del aire); valor bajo (colores fríos) = aire más limpio. Comparable entre los territorios disponibles. Selecciona un departamento para ver la contribución relativa de cada driver.',
			en: 'The map shows air quality in each hexagon, measured as mean PM2.5 concentration (fine particles < 2.5 µm) and decomposed into four drivers: regional fire, climate, terrain and vegetation. High value (warm/red colours) = higher PM2.5 concentration (worse air quality); low value (cool colours) = cleaner air. Comparable across available territories. Select a department to view the relative contribution of each driver.',
			gn: "Mapa ohechauka tyre'ỹ aire hexágono-pe, PM2.5 mba'épe ha drivers: tata, ára, yvy ha ka'aguy. Valor yvate (pyta) = yvate PM2.5 (aire vai); michĩ (sovy) = aire potĩ. Ojoguáva tetã kuéra ojoguávape.",
			pt: 'O mapa mostra a qualidade do ar em cada hexágono, medida como concentração média de PM2.5 (partículas finas < 2,5 µm) e decomposta em quatro drivers: fogo regional, clima, terreno e vegetação. Valor alto (cores quentes/vermelhas) = maior concentração de PM2.5 (pior qualidade do ar); valor baixo (cores frias) = ar mais limpo. Comparável entre os territórios disponíveis. Selecione um departamento para ver a contribuição relativa de cada driver.',
		},
		implications: {
			es: 'La intensidad de fuego regional es el driver dominante de PM2.5: las quemas agrícolas y forestales en provincias vecinas y países limítrofes elevan la concentración de partículas finas incluso en zonas sin deforestación local. Las zonas con alta contribución climática son sensibles a eventos de inversión térmica que atrapan contaminantes. La vegetación actúa como filtro natural — la pérdida de cobertura arbórea reduce la capacidad de depuración del aire.',
			en: 'Regional fire intensity is the dominant PM2.5 driver: agricultural and forest burns in neighbouring provinces and countries raise fine particle concentrations even in zones without local deforestation. Zones with high climate contribution are sensitive to thermal inversion events that trap pollutants. Vegetation acts as a natural filter — tree cover loss reduces air purification capacity.',
			gn: "Tata regional = driver dominante PM2.5: tata agrícola ha forestal provincias ha países ndive oñemboyvate partículas. Ára ohechauka inversión térmica. Ka'aguy = filtro natural; oguejyvo yvyra cobertura oguejy capacidad aire.",
			pt: 'A intensidade do fogo regional é o driver dominante do PM2.5: as queimadas agrícolas e florestais em províncias vizinhas e países limítrofes elevam a concentração de partículas finas mesmo em zonas sem desmatamento local. As zonas com alta contribuição climática são sensíveis a eventos de inversão térmica que aprisionam poluentes. A vegetação atua como filtro natural — a perda de cobertura arbórea reduz a capacidade de purificação do ar.',
		},
		method: {
			es: `El mapa y las clasificaciones operan sobre la concentración CRUDA de PM2.5 (µg/m³, media anual) — sin scores intermedios. Clasificación de exposición según la Guía de Calidad del Aire OMS 2021 y sus metas intermedias: ≤10 Muy baja (cumple IT-4) · 10–15 Baja (IT-3) · 15–25 Moderada (IT-2) · 25–35 Alta (IT-1) · >35 Muy alta (excede IT-1). La guía anual OMS es 5 µg/m³. Descomposición por machine learning (LightGBM, SHAP feature attribution). Fuente primaria: Atmospheric Composition Analysis Group (ACAG) V6.GL.02 (Dalhousie University, van Donkelaar et al. 2021), panel 1998–2022, resolución 0.01° (~1 km). Modelo entrenado con 31 covariables ambientales (R² = 0.93 en validación cruzada espacial leave-one-department-out). Drivers agrupados por SHAP: fuego regional (contribución dominante, ΔR² = 0.195), clima (precipitación, temperatura), terreno (elevación, pendiente) y vegetación (NDVI, NPP). Celdas res-7 sin cobertura del modelo (borde del territorio, zonas urbanas excluidas del panel) se imputan con la media de vecinos en anillo k≤2 (~7 km); las celdas sin vecinos cubiertos quedan sin dato. El toggle temporal compara periodo 2001–2010 vs 2013–2022. Resolución espacial: H3 resolución 9.`,
			en: `The map and classifications operate on the RAW PM2.5 concentration (µg/m³, annual mean) — no intermediate scores. Exposure classification follows the WHO 2021 Air Quality Guideline and its interim targets: ≤10 Very low (meets IT-4) · 10–15 Low (IT-3) · 15–25 Moderate (IT-2) · 25–35 High (IT-1) · >35 Very high (exceeds IT-1). The WHO annual guideline is 5 µg/m³. Machine-learning decomposition (LightGBM, SHAP feature attribution). Primary source: Atmospheric Composition Analysis Group (ACAG) V6.GL.02 (Dalhousie University, van Donkelaar et al. 2021), panel 1998–2022, resolution 0.01° (~1 km). Model trained with 31 environmental covariates (R² = 0.93 in spatial leave-one-department-out cross-validation). Drivers grouped by SHAP: regional fire (dominant contribution, ΔR² = 0.195), climate (precipitation, temperature), terrain (elevation, slope) and vegetation (NDVI, NPP). Res-7 cells not covered by the model (territory border, urban zones excluded from the panel) are imputed with the mean of k≤2 ring neighbours (~7 km); cells with no covered neighbours remain blank. Temporal toggle compares period 2001–2010 vs 2013–2022. Spatial resolution: H3 resolution 9.`,
		},
	},
	deforestation_dynamics: {
		howToRead: {
			es: 'Cada hexágono muestra la tasa de pérdida forestal observada en ese punto exacto (pixel Landsat 30m). Colores cálidos = mayor pérdida forestal reciente (2015–2024). El toggle temporal permite comparar con la línea base (2001–2010): el modo "Cambio" muestra si la deforestación aceleró (rojo) o frenó (verde) respecto al periodo base. Comparable entre los territorios disponibles.',
			en: 'Each hexagon shows the forest loss rate observed at that exact point (Landsat 30m pixel). Warm colours = greater recent forest loss (2015–2024). The temporal toggle allows comparison with the baseline (2001–2010): "Change" mode shows whether deforestation accelerated (red) or slowed (green) relative to the baseline period. Comparable across available territories.',
			gn: "Peteĩ-peteĩ hexágono ohechauka ka'aguy reiguáva tasa pixel Landsat 30m-pe. Pytã = yvate pérdida forestal (2015–2024). Toggle temporal oñembojoaju línea base (2001–2010). Ojoguáva tetã kuéra ojoguávape.",
			pt: 'Cada hexágono mostra a taxa de perda florestal observada naquele ponto exato (pixel Landsat 30m). Cores quentes = maior perda florestal recente (2015–2024). O toggle temporal permite comparar com a linha de base (2001–2010): o modo "Mudança" mostra se o desmatamento acelerou (vermelho) ou desacelerou (verde) em relação ao período base. Comparável entre os territórios disponíveis.',
		},
		implications: {
			es: "Las zonas con alta tasa de pérdida sostenida representan frentes de deforestación activos donde la conversión del bosque nativo continúa. Las zonas donde la deforestación frenó (delta negativo) pueden reflejar el efecto de regulación ambiental (Ley de Bosques en Argentina, leyes forestales en Paraguay) o el agotamiento del recurso. Las zonas que aceleraron requieren atención prioritaria de fiscalización.",
			en: "Zones with a sustained high loss rate represent active deforestation fronts where native forest conversion continues. Zones where deforestation slowed (negative delta) may reflect environmental regulation (Argentina's Forest Law, Paraguay's forestry laws) or resource depletion. Zones that accelerated require priority enforcement attention.",
			gn: "Yvate pérdida forestal sostenida = frente deforestación activo. Delta negativo = regulación ambiental (Ley Bosques) o agotamiento. Yvate aceleración = fiscalización prioritaria.",
			pt: 'Zonas com alta taxa de perda sustentada representam frentes de desmatamento ativos onde a conversão da floresta nativa continua. Zonas onde o desmatamento desacelerou (delta negativo) podem refletir o efeito da regulação ambiental (Lei de Florestas na Argentina, leis florestais no Paraguai) ou o esgotamento do recurso. Zonas que aceleraram requerem atenção prioritária de fiscalização.',
		},
		method: {
			es: `Score de deforestación normalizado con goalpost fijo: tasa de pérdida anual [0, 5] %/año (0 = sin pérdida, 100 = pérdida máxima). Fuente: Hansen Global Forest Change v1.12 (University of Maryland / Google), derivado de series temporales Landsat a 30m, cobertura 2001–2024. Estadísticas zonales verdaderas: cada hexágono H3 resolución 9 (~0.1 km²) recibe el conteo de píxeles de pérdida por año dentro de su polígono (no centroide). La tasa se calcula como fracción de píxeles con pérdida detectada en cada periodo. Línea base: 2001–2010; actual: 2015–2024. Pérdida acumulada goalpost: [0, 40]%. Actualización automática vía GitHub Actions cuando Hansen publica nuevos datos (~abril de cada año).`,
			en: `Normalised deforestation score with fixed goalpost: annual loss rate [0, 5] %/year (0 = no loss, 100 = maximum loss). Source: Hansen Global Forest Change v1.12 (University of Maryland / Google), derived from Landsat time series at 30m, coverage 2001–2024. True zonal statistics: each H3 resolution 9 hexagon (~0.1 km²) receives the pixel count of annual loss within its polygon (not centroid). Rate calculated as the fraction of pixels with detected loss in each period. Baseline: 2001–2010; current: 2015–2024. Cumulative loss goalpost: [0, 40]%. Automatic update via GitHub Actions when Hansen releases new data (~April each year).`,
		},
	},
};

export function getMethodologyContent(analysisId: string): LocalizedMethodologyContent | null {
	return ANALYSIS_CONTENT[analysisId] ?? null;
}

/**
 * `method` exists only in es/en — see LocalizedMethodologyContent above.
 *
 * Returns the text plus the locale it fell back *from*, so the render site can say so
 * rather than silently serving Spanish inside a Portuguese page. Keeping the asymmetry
 * here means the four render sites don't each encode it: once `method` gains pt/gn,
 * `fallbackFrom` goes null everywhere and the notices disappear on their own.
 */
export function resolveMethod(
	method: LocalizedMethodologyContent['method'],
	locale: Locale
): { text: string; fallbackFrom: Locale | null } {
	if (locale === 'es' || locale === 'en') return { text: method[locale], fallbackFrom: null };
	return { text: method.es, fallbackFrom: locale };
}

export function listMethodologyIds(): string[] {
	return Object.keys(ANALYSIS_CONTENT);
}
